final/final/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('online/',include('online_quizz.urls')),
]

final/online_quizz/urls.py
from django.urls import path
from . import views
app_name = "online_quizz"
urlpatterns = [
    path('home', views.home_page, name='home_page'),
    path('login',views.student_login,name='student_login'),
    path('signup',views.register_page,name='register_page'),
    path('courses/', views.course_list, name='course_list'),
    path('details/<int:pk>/', views.course_detail, name='course_detail'),
    path('evaluate/<int:course_id>/', views.evaluate_results, name='evaluate_results'),
    path('logout', views.logout_, name='logout'),
    path('dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('profile/', views.view_profile, name='profile'),
    path('teacher-view/', views.teacher_view, name='teacher_view'),
    path('teacher/courses/', views.teacher_courses, name='teacher_courses'),
    path('teacher/course/<int:course_id>/', views.course_details, name='course_details'),
    path('teacher/course/add/', views.add_course, name='add_course'),
    path('teacher/course/update/<int:course_id>/', views.update_course, name='update_course'),
    path('teacher/course/delete/<int:course_id>/', views.delete_course, name='delete_course'),
    path('teacher/course/<int:course_id>/question/add/', views.add_question, name='add_question'),
    path('teacher/course/<int:course_id>/question/delete/<int:question_id>/', views.delete_question, name='delete_question'),
   
]

final/online_quizz/models.py
from django.db import models
from django.contrib.auth.models import Group

# Create your models here.
from django.contrib.auth.models import User

class Course(models.Model):
   course_name = models.CharField(max_length=50)
   description = models.CharField(max_length=200)
   total_marks = models.PositiveIntegerField()
   def __str__(self):
        return f'{self.course_name},{self.description}' 

class Question(models.Model):
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    marks=models.PositiveIntegerField()
    question_number = models.IntegerField(default=1)
    question=models.CharField(max_length=600)
    option1=models.CharField(max_length=200)
    option2=models.CharField(max_length=200)
    option3=models.CharField(max_length=200)
    option4=models.CharField(max_length=200)
    cat=(('Option1','Option1'),('Option2','Option2'),('Option3','Option3'),('Option4','Option4'))
    answer=models.CharField(max_length=200,choices=cat)

class Result(models.Model):

    group = models.ForeignKey(Group, on_delete=models.CASCADE, default=1)
    exam = models.ForeignKey(Course, on_delete=models.CASCADE)
    marks = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now=True)
    percentage = models.FloatField()


    def __str__(self):
        return f"Result for {self.exam.course_name}"

final/online_quizz/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth import  authenticate,login,logout
from django.contrib.auth.decorators import login_required ,permission_required
from django.contrib.auth.models import User, Group
from .models import Course,Question,Result


def home_page(request):
    return render(request,"online_quizz/main.html")

def student_login(request):
    error_message = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(password)
        print(username)
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            # user_ = customer.objects.get(user=user)
            teacher = Group.objects.get(name='teachers')
            student = Group.objects.get(name='students')
            if teacher in user.groups.all():
                #redirect to teacher homepage
                return redirect('online_quizz:teacher_dashboard')
            if student in user.groups.all():
                #redirect to student homepage
                return  redirect('online_quizz:course_list')
            return redirect('online_quizz:home_page',)
            # print(username,password,user.id)
        else:
            error_message = 'Invalid login credentials'
    return render(request,'online_quizz/student_login.html',{'error_message':error_message})
def register_page(request): 
    error_message = ''
    if request.method == "POST":
        username_ = request.POST.get('username','')
        email_ = request.POST.get('email','')
        password_ = request.POST.get('password','')
        confirm_password_ = request.POST.get('confirm_password','')
        if password_ == confirm_password_:
            if len(User.objects.filter(username=username_)) > 0:
                return redirect('online_quizz:register_page')
            else:
                if len(User.objects.filter(email=email_)) > 0:
                    return redirect('online_quizz:register_page')
                else:
                    user = User.objects.create_user(username=username_, email=email_)
                    user.set_password(password_)
                    user.save()
                    error_message = 'Registration successful! You can now log in.'
                    return redirect('online_quizz:home_page')
        else:
            error_message = 'Password and confirm password do not match.'
      
    return render(request, 'online_quizz/student_sign.html',  {'error_message': error_message})

@permission_required('online_quizz.view_course',login_url='online_quizz:student_login')
def course_list(request):
    courses = Course.objects.all()
    return render(request, 'online_quizz/course_list.html', {'courses': courses})

@permission_required('online_quizz.view_question',login_url='online_quizz:student_login')
def course_detail(request, pk):
    course = Course.objects.get(pk=pk)
    questions = Question.objects.filter(course=course)
    return render(request, 'online_quizz/course_detail.html', {'course': course, 'questions': questions})

@permission_required('online_quizz.view_question',login_url='online_quizz:student_login')
def evaluate_results(request, course_id):
    if request.method == 'POST':
        course = get_object_or_404(Course, id=course_id)
        student_group = request.user.groups.first()
        student_answers = request.POST
        total_marks = 0
        obtained_marks = 0

        for question in course.question_set.all():
            question_id = str(question.id)
            selected_answer = student_answers.get(f"question_{question.id}")
            print(selected_answer)
            print(question.answer)
            if selected_answer == question.answer:
                obtained_marks += question.marks

            total_marks += question.marks

        percentage_value = (obtained_marks / total_marks) * 100

        result = Result.objects.create(group=Group.objects.get(name='students'), exam=course, marks=obtained_marks, percentage=percentage_value)
        return render(request, 'online_quizz/result.html', {'result': result, 'total_marks': total_marks, 'percentage': percentage_value})

    else:
        course = get_object_or_404(Course, id=course_id)
        questions = course.question_set.all()
        return render(request, 'online_quizz/course_detail.html', {'course': course, 'questions': questions})

def logout_(request):
    logout(request)
    return redirect('online_quizz:home_page')
# @permission_required('online_quizz.view_dashboard',login_url='online_quizz:student_login')
@login_required (login_url='online_quizz:student_login')
def teacher_dashboard(request):

    students = User.objects.filter(groups__name='students')
    courses = Course.objects.all()
    student_count = students.count()
    course_count = Course.objects.count()
    context = {
        'students': students,
        'courses': courses,
        'student_count':student_count,
        'course_count':course_count,
        
    }

    return render(request, 'online_quizz/teacher_dashboard.html', context)
@login_required (login_url='online_quizz:student_login')
def view_profile(request):
    user = request.user
    results = Result.objects.filter(group__name='students')  # Filter results by group name 'students'

    quizzes_count = 0
    overall_percentage = 0.0

    for result in results:
        if result.percentage is not None:
            overall_percentage += result.percentage
            quizzes_count += 1

    overall_percentage = overall_percentage / quizzes_count if quizzes_count > 0 else 0.0

    profile_data = []
    for result in results:
        percentage = result.percentage if result.percentage is not None else 0.0
        total_marks = sum(question.marks for question in result.exam.question_set.all())

        profile_data.append({
            'course_name': result.exam.course_name,
            'marks': result.marks,
            'percentage': percentage,
            'date': result.date,
            'total_marks':total_marks

        })
    
    return render(request, 'online_quizz/profile.html', {'profile_data': profile_data, 'overall_percentage': overall_percentage})
@login_required (login_url='online_quizz:student_login')
def teacher_view(request):
    students = User.objects.filter(groups__name='students')  # Get all users in 'students' group
    student_data = []

    for student in students:
        results = Result.objects.filter(group__name='students', exam__in=Course.objects.all(), group__user=student)
        total_marks = sum(result.marks for result in results)
        overall_percentage = (total_marks / (results.count() * 100)) * 100 if results.count() > 0 else 0

        student_data.append({
            'student': student,
            'results': results,
            'total_marks': total_marks,
            'overall_percentage': overall_percentage,
        })

    return render(request, 'online_quizz/teacher_view.html', {'student_data': student_data})
@permission_required('online_quizz.view_course',login_url='online_quizz:student_login')
def teacher_courses(request):
    courses = Course.objects.all()
    return render(request, 'online_quizz/teacher_courses.html', {'courses': courses})
@permission_required('online_quizz.view_question',login_url='online_quizz:student_login')
def course_details(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    questions = course.question_set.all()
    return render(request, 'online_quizz/course_details.html', {'course': course, 'questions': questions})
@permission_required('online_quizz.add_course',login_url='online_quizz:student_login')
def add_course(request):
    if request.method == 'POST':
        # Process form data and save the new course
        course_name = request.POST['course_name']
        description = request.POST['description']
        total_marks = request.POST['total_marks']

        course = Course(course_name=course_name, description=description, total_marks=total_marks)
        course.save()

        return redirect('online_quizz:teacher_courses')

    return render(request, 'online_quizz/add_course.html')
@permission_required('online_quizz.change_course',login_url='online_quizz:student_login')
def update_course(request, course_id):
    course = get_object_or_404(Course, id=course_id)

    if request.method == 'POST':
        # Update course details
        course.course_name = request.POST['course_name']
        course.description = request.POST['description']
        course.total_marks = request.POST['total_marks']
        course.save()

        return redirect('online_quizz:course_details', course_id=course.id)

    return render(request, 'online_quizz/update_course.html', {'course': course})
@permission_required('online_quizz.delete_course',login_url='online_quizz:student_login')
def delete_course(request, course_id):
    course = get_object_or_404(Course, id=course_id)

    if request.method == 'POST':
        # Delete the course
        course.delete()
        return redirect('online_quizz:teacher_courses')

    return render(request, 'online_quizz/delete_course.html', {'course': course})
@permission_required('online_quizz.add_question',login_url='online_quizz:student_login')
def add_question(request, course_id):
    course = get_object_or_404(Course, id=course_id)

    if request.method == 'POST':
        # Process form data and save the new question
        question = request.POST['question']
        marks = request.POST['marks']
        question_number = request.POST['question_number']
        option1 = request.POST['Option1']
        option2 = request.POST['Option2']
        option3 = request.POST['Option3']
        option4 = request.POST['Option4']
        answer = request.POST['answer']

final/online_quizz/templates/online_quizz/add_question.html
<!DOCTYPE html>
<html>
<head>
    <title>Add question</title>
</head>
<body>
   
</body>
</html>
<!DOCTYPE html>
<html>
<head>
	<title>Course List</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<!------ Include the above in your HEAD tag ---------->
	<style>
		body {
				font-family: Arial, sans-serif;
				margin: 0;
				padding: 0;
			}
		.cor{
					
			float: left;
					
			}	
		header {
			background-color: #333;
			color: #fff;
			padding: 10px;
			display: flex;
			justify-content: space-between;
			align-items: center;
			width: 100%;
			height: 100%;
		}

		header h1 {
			margin: 0;
		}

		.user-container {
			display: flex;
			align-items: center;
		}

		.user-greeting {
			margin-right: 10px;
		}

		.logout-link,
		.login-link {
			color: #fff;
			text-decoration: none;
			border: 1px solid #fff;
			padding: 5px 10px;
			border-radius: 5px;
		}

		.logout-link:hover,
		.login-link:hover {
			background-color: #fff;
			color: #333;
		}



        .footer {
			position: absolute;
			bottom: 0;
			width: 100%;
			background-color: #333;
			color: #fff;
			padding: 20px;
			text-align: center;
			margin-top: 20px;
		}

		.footer-container {
			display: flex;
			justify-content: space-between;
			align-items: center;
			flex-wrap: wrap;
		}

		.footer-icons {
			display: flex;
			align-items: center;
		}

		.footer-icons a {
			color: #fff;
			text-decoration: none;
			margin-right: 10px;
		}

		.footer-icons i {
			font-size: 18px;
		}

		.footer-icons a:hover {
			color: #ccc;
		}


				h1 {
					margin: 20px 0;
					text-align: center;
				}

				.card {
			margin: 20px;
		}


		.card {
			margin: 20px;
		}

		.course-list {
			display: flex;
			flex-wrap: wrap;
			list-style-type: none;
			margin: 0;
			padding: 0;
			justify-content: center;
		}

		.course-item {
			padding: 10px;
			border: 1px solid #ccc;
			margin: 10px;
			width: 300px;
			display: flex;
			flex-direction: column;
			align-items: center;
			text-align: center;
			background-color: #f2f2f2;
		}

		.course-item:hover {
			background-color: #e0e0e0;
		}

		.course-link {
			text-decoration: none;
			color: #333;
			display: flex;
			flex-direction: column;
			align-items: center;
		}

		.course-info {
			display: flex;
			flex-direction: column;
			align-items: center;
		}

		.course-image {
			width: 200px;
			height: auto;
			margin-bottom: 10px;
		}

		.course-details {

			margin-bottom: 10px;
		}

		.course-name {
			font-weight: bold;
		}

		.view-button {
			padding: 8px 16px;
			background-color: #333;
			color: #fff;
			border: none;
			cursor: pointer;
		}

		.view-button:hover {
			background-color: #666;
		}

		.dropdown {
			position: relative;
			display: inline-block;
		}
		
		.dropbtn {
			background-color: #333;
			color: #fff;
			border: none;
			padding: 8px 16px;
			border-radius: 5px;
			cursor: pointer;
		}
		
		.dropdown-content {
			display: none;
			position: absolute;
			background-color: #f9f9f9;
			min-width: 160px;
			box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
			z-index: 1;
		}
		
		.dropdown-content a {
			color: #333;
			padding: 12px 16px;
			text-decoration: none;
			display: block;
		}
		
		.dropdown-content a:hover {
			background-color: #ccc;
		}
		
		.show {
			display: block;
		}
		.objects{
			display: flex;
			flex-direction: column;
			justify-content: space-evenly;
			align-items: center;
			align-content: space-evenly;
			border:  black 1px solid;

		}
		body {
			overflow-x: hidden;
		 }
		
		/* Toggle Styles */
		
		#wrapper {
			padding-left: 0;
			-webkit-transition: all 0.6s ease;
			-moz-transition: all 0.6s ease;
			-o-transition: all 0.6s ease;
			transition: all 0.6s ease;
			
		}
		
		#wrapper.toggled {
			padding-left: 200px;
		}
		
		#sidebar-wrapper {
			z-index: 1000;
			position: fixed;
			left: 250px;
			
			width: 0;
			height: 500px;
			margin-left: -250px;
			overflow-y: auto;
			background-color:#312A25 !Important;
		   
			-webkit-transition: all 0.5s ease;
			-moz-transition: all 0.5s ease;
			-o-transition: all 0.5s ease;
			transition: all 0.5s ease;
		}
		
		#wrapper.toggled #sidebar-wrapper {
			width: 0;
		}
		
		#page-content-wrapper {
			width: 100%;
			position: absolute;
			padding: 10px;
		}
		
		#wrapper.toggled #page-content-wrapper {
			position: absolute;
			margin-left:-250px;
		}
		
		/* Sidebar Styles */
		
		.sidebar-nav {
			position: absolute;
			top: 0;
			right:15px;
			width: 200px;
			margin: 0;
			padding: 0;
			list-style: none;
			z-index: -1;
		}
		
		.sidebar-nav li {
			text-indent: 20px;
			line-height: 40px;
		}
		
		.sidebar-nav li a {
			display: block;
			text-decoration: none;
			color: #999999;
		}
		
		.sidebar-nav li a:hover {
			text-decoration: none;
			color: #fff;
			background: #312A25;
		}
		
		.sidebar-nav li a:active,
		.sidebar-nav li a:focus {
			text-decoration: none;
		}
		
		.sidebar-nav > .sidebar-brand {
			height: 65px;
			font-size: 18px;
			line-height: 60px;
		}
		
		.sidebar-nav > .sidebar-brand a {
			color: #999999;
		}
		
		.sidebar-nav > .sidebar-brand a:hover {
			color: #fff;
			background: none;
		}
		
		@media(min-width:768px) {
			#wrapper {
				padding-left: 220px;
			}
		
			#wrapper.toggled {
				padding-left: 0;
			}
		
			#sidebar-wrapper {
				width: 200px;
			}
		
			#wrapper.toggled #sidebar-wrapper {
				width: 40px;
				
				
			}
		
		#wrapper.toggled span {
				visibility:hidden;
				
			}
		  #wrapper.toggled   i {
		 float:right;
		 } 
		
			#page-content-wrapper {
				padding: 20px;
				position: relative;
			}
		
			#wrapper.toggled #page-content-wrapper {
				position: fixed;
				margin-right: 0;
			}
		}
		
		
		@media(max-width:414px) {
		
		#wrapper.toggled #page-content-wrapper {
			position: absolute;
			margin-right:60px;
		}
		
		#wrapper.toggled {
			padding-right: 60px;
		}
		
		 #wrapper {
				padding-left: 20px;
			}
		
			#wrapper.toggled {
				padding-left: 0;
			}
		
			#sidebar-wrapper {
				width: 50px;
			}
		
			#wrapper.toggled #sidebar-wrapper {
				width: 140px;
				
				
			}
			
			#wrapper.toggled span {
				visibility:visible;
				position:relative;
				left:70px;
				bottom:13px;
				
			}
		
		#wrapper span {
				visibility:hidden;
				
			}
		  #wrapper.toggled   i {
		 float:right;
		 } 
		 
		  #wrapper   i {
		 float:right;
		 } 
		
			#page-content-wrapper {
				padding: 5px;
				position: relative;
			}
		
			#wrapper.toggled #page-content-wrapper {
				position: relative;
				margin-right: 0;
			}
		
		
		
		
		}
		
		#submit-btn {
			margin-bottom: 50px;
		}
	</style>
</head>
<body>
	<header>
		<h1>Online Quizz</h1>
		{% if user.is_authenticated %}
			<div class="user-container">
				<div class="dropdown">
					<button onclick="toggleDropdown()" class="dropbtn">{{ user.username }}   <i class="fa-solid fa-user"></i></button>
					<div id="dropdown-content" class="dropdown-content">
						<a href="{% url 'online_quizz:logout'%}">Logout</a>
					</div>
				</div>
			</div>
		{% else %}
			<div class="user-container">
				<a href="#" class="login-link">Login</a>
			</div>
		{% endif %}
	</header>
	<div class="container">
		<div class="row">
			<h1>Teacher Dashboard</h1>
			<hr/>
			
			<div id="wrapper">
			<!-- Sidebar -->
                <div id="sidebar-wrapper">
                    <ul class="sidebar-nav" style="margin-left:0;">
                        <li class="sidebar-brand">
                            
                            <a href="#menu-toggle"  id="menu-toggle" style="margin-top:20px;float:right;" > <i class="fa fa-bars " style="font-size:20px !Important;" aria-hidden="true" aria-hidden="true"></i> </a>
                            
                        </li>
                        <li>
                            <a href="{% url 'online_quizz:teacher_dashboard' %}"><i class="fa-solid fa-house-user"></i> <span style="margin-left:10px;">Dashboard</span>  </a>
                        </li>
                        <!-- <li>
                            <a href="#"> <i class="fa fa-play-circle-o " aria-hidden="true"> </i> <span style="margin-left:10px;">courses</span> </a>
                        </li> -->
                        <!-- <li>
                            <a href="#"> <i class="fa-solid fa-clipboard-question"></i> <span style="margin-left:10px;"> questions</span> </a>
                        </li> -->
                        <li>
                            <a href="{% url 'online_quizz:teacher_courses' %}"> <i class="fa-solid fa-book"></i> <span style="margin-left:10px;"> courses</span> </a>
                        </li>
                        <!-- <li>
                            <a href="#"><i class="fa fa-info-circle " aria-hidden="true"> </i> <span style="margin-left:10px;">Section </span> </a>
                        </li> -->
                        <li>
                            <a href="#"> <i class="fa-solid fa-right-from-bracket"></i> <span style="margin-left:10px;"> logout</span> </a>
                        </li>
                    </ul>
                </div>
                <!-- /#sidebar-wrapper -->
        
                <!-- Page Content -->
                <h2>Add Question</h2>
                <form method="POST" action="{% url 'online_quizz:add_question' course_id=course.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="question">Question:</label>
                        <textarea class="form-control" id="question" name="question" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="marks">Marks</label>
                        <input type="number" class="form-control" id="marks" name="marks">
                    </div>
                    <div class="form-group">
                        <label for="question_number">Question Number</label>
                        <input type="text" class="form-control" id="question_number" name="question_number">
                    </div>
                    <div class="form-group">
                        <label for="Option1">Option 1:</label>
                        <input type="text" class="form-control" id="option1" name="Option1">
                    </div>
                    <div class="form-group">
                        <label for="Option2">Option 2:</label>
                        <input type="text" class="form-control" id="option2" name="Option2">
                    </div>
                    <div class="form-group">
                        <label for="Option3">Option 3:</label>
                        <input type="text" class="form-control" id="option3" name="Option3">
                    </div>
                    <div class="form-group">
                        <label for="option4">Option 4:</label>
                        <input type="text" class="form-control" id="option4" name="Option4">
                    </div>
                    <div class="form-group">
                        <label for="answer">Answer:</label>
                        <select class="form-control" id="answer" name="answer">
                            <option value="Option1">Option 1</option>
                            <option value="Option2">Option 2</option>
                            <option value="Option3">Option 3</option>
                            <option value="Option4">Option 4</option>
                        </select>
                    </div>
                    <button id="submit-btn" type="submit" class="btn btn-primary submit-button">Submit</button>
                </form>
			</div>				 
			<script>
				$("#menu-toggle").click(function(e) {
					e.preventDefault();
					$("#wrapper").toggleClass("toggled");
				});
			</script>	
						
	
		
		</div>
	</div>
	

	<script>
		function toggleDropdown() {
			var dropdownContent = document.getElementById("dropdown-content");
			dropdownContent.classList.toggle("show");
		}
		
		window.onclick = function(event) {
			if (!event.target.matches('.dropbtn')) {
				var dropdowns = document.getElementsByClassName("dropdown-content");
				for (var i = 0; i < dropdowns.length; i++) {
					var openDropdown = dropdowns[i];
					if (openDropdown.classList.contains('show')) {
						openDropdown.classList.remove('show');
					}
				}
			}
		}
		
	</script>
	
</body>
</html>

final/online_quizz/templates/online_quizz/course_details.html
{% extends 'online_quizz\dashborad_base.html' %}
{% block title %}
    Course Details
{% endblock %}
{% block content %}
    <style>
        .container {
            padding: 10px;
            margin-bottom: 50px;
            
        
        }
        h2 {
            color: #333;
            font-size: 24px;
            margin-bottom: 10px;
        }
        p {
            color: #666;
            font-size: 16px;
            margin-bottom: 5px;
        }

        h3 {
            color: #333;
            font-size: 20px;
            margin-bottom: 10px;
        }

        ul {
        list-style-type: disc;
        margin-left: 20px;
        }

        li {
        color: #666;
        font-size: 14px;
        margin-bottom: 5px;
        }

        a {
        color: #007bff;
        text-decoration: none;
        }

        a:hover {
        text-decoration: underline;
        }
        .button-container {
        margin-top: 10px;
        }
        .button-container button {
         margin-right: 10px;
        }
        button {
        background-color: #007bff;
        color: #fff;
        border-radius: 5px;
        padding: 4px 8px;
        font-size: 14px;
        cursor: pointer;
        spacing:10px;
        }
          
        button:hover {
        background-color: #0056b3;
          }
    </style>
    <div class="container">
        <h2>Course Name: {{ course.course_name }}</h2>
        <p>Description: {{ course.description }}</p>
        <p>Total Marks: {{ course.total_marks }}</p>
        <h3>Questions:</h3>
        <ul>
            {% for question in questions %}
            <h3>{{question.question_number}} . {{ question.question }} --   <a class="btn btn-danger" href="{% url 'online_quizz:delete_question' course.id question.id %}">Delete</a></h3>
            {% endfor %}
        </ul>
    </div>
    <div class="button-container">
        <a href="{% url 'online_quizz:add_question' course.id %}"><button type="button">Add Question</button></a>
        <a href="{% url 'online_quizz:update_course' course.id %}"><button type="button">Update Course</button></a>
        <a href="{% url 'online_quizz:delete_course' course.id %}"><button type="button">Delete Course</button></a>
    </div>
{% endblock %}

final/online_quizz/templates/online_quizz/course_list.html
{% extends 'online_quizz\base.html' %}
{% block title %}
	course list
{% endblock %}
{% block content %}
    {% load static %}
	<style>
		.cor h1{
			text-align: center;
			margin: 0 auto;
			max-width: 800px;
		}
		
		.course-list {
			list-style-type: none;
			padding: 0;
			display: grid;
			grid-template-columns: 1fr;
			grid-gap: 10px;
			margin-top: 20px;
		}
		
		.course-item {
			padding: 10px;
			background-color: #f5f5f5;
			text-align: center;
			border-radius: 5px;
		}
		.course-item h4{
			margin-right: 10px;
		}
		.card {
			margin: 0 auto;
			max-width: 800px;
			background-color: #fff;
			padding: 20px;
		}
	</style>
	
	<div class="cor">
		<h1>Courses:</h1>
	</div>
	
	<div class="card">
		<ul class="course-list">
			{% for course in courses %}
				<li class="course-item">
					<h4>{{ course.course_name }}</h4>
					<a href="{% url 'online_quizz:course_detail' pk=course.pk %}" class="btn btn-primary">View Course</a>
				</li>
			{% endfor %}
		</ul>
	</div>
{% endblock %}