day_1/day_1/urls.py
from django.contrib import admin 
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include('say_hello.urls')),
    path('fibonacci/',include('Fibonacci.urls')),
    path('rock/',include('rock_paper_scissors.urls')),
    path('gradebook/',include('gradebook.urls')),
    path('employee/',include('Employees.urls')),
   
]

day_1/gradebook/urls.py
from django.urls import path
from . import views

app_name='gradebook'

urlpatterns = [
    path('student/add/<str:name_>',views.new_student,name='new_student'),
    path('student/<int:id>', views.student_detail, name='student_detail'),
    path('student/<int:id>/add', views.add_marks, name='add_marks'),
    path('student/<int:id>/delete', views.delete_marks, name='delete_marks'),
    path('student/update/<int:id>', views.update_marks, name='update_marks')

]

day_1/gradebook/models.py
# from django.db import models

# Create your models here.
from django.db import models

class Student(models.Model):
    name = models.CharField(max_length = 256)

    def __str__(self):
        return f' {self.name}'

class Marks(models.Model):
    subject_name = models.CharField(max_length = 128)
    score = models.IntegerField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    #having a list of Marks inside every student
    #is the same as having a student inside every Mark

    def __str__(self):
        return f'{self.student} - {self.subject_name} - {self.score}'

day_1/gradebook/views.py
# from django.shortcuts import render,redirect
# from .models import Student,Marks
# # Create your views here.

# def student_details(request,id):#read
#     student_=Student.objects.get(pk=id)
#     marks = Marks.objects.filter(student=student_)
#     context ={'student':student_,'marks':marks}
#     return render(request,'gradebook/marksheet.html',context)
# def add_marks(request,id): #create
#     student_ = Student.objects.get(pk=id)
#     sub_name = request.POST.get('sub_name')
#     score_ =request.POST.get('score')

#     marks =Marks(student=student_,subject_name=sub_name,score=score_)
#     marks.save()
#     return redirect('gradebook:student_details',student_.id)
# def delete_marks(request, id):
#     #this is the Delete of crud
#     marks = Marks.objects.get(pk=id)
#     marks.delete()
#     return redirect('gradebook:student_details', marks.student.id)
from django.shortcuts import render, redirect
from .models import Student, Marks
from django.http  import HttpResponse
# Create your views here.

def new_student(request,name_):
    student=Student(name=name_)
    student.save()
    return HttpResponse('ok')
    

def student_detail(request, id):
    #this is the R of CRUD
    student_ = Student.objects.get(pk=id)
    #SELECT * FROM STUDENT WHERE <INSERT PRIMARY KEY HERE>=id
    marks = Marks.objects.filter(student=student_)
    #SELECT * FROM MARKS WHERE STUDENT=(SELECT * FROM STUDENT
    # WHERE <INSERT PRIMARY KEY HERE>=id)

    context = {'student': student_, 'marks': marks}
    return render(request, 'gradebook\marksheet.html', context)

def add_marks(request, id):
    #this is the C of CRUD
    student_ = Student.objects.get(pk=id)

    sub_name_ = request.POST.get('sub_name')
    score_ = request.POST.get('score')

    marks = Marks(student=student_, subject_name=sub_name_, score=score_)
    marks.save()
    return redirect('gradebook:student_detail', student_.id)

def delete_marks(request, id):
    #this is the D of crud
    marks = Marks.objects.get(pk=id)
    marks.delete()
    return redirect('gradebook:student_detail', marks.student.id)
def update_marks(request,id):
    student_ =Student.objects.get(pk=id)
    marks = Marks.objects.filter(student=student_)

    name = request.POST.get('name')
    update_name = request.POST.get('update_name')
    update_score = request.POST.get('update_score')
    for item in marks:
        if item.subject_name == name:
            item.subject_name = update_name
            item.score = update_score
            item.save()
    return redirect('gradebook:student_detail', student_.id)
    # return HttpResponse(f'{marks[]}')
    

    # marks.update()

    #user = harish,user@2428

day_1/gradebook/templates/gradebook/marksheet.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Models</title>
    </head>
    <body>
        <h1>{{student.name}}</h1>
        <table>
            {% for item in marks %}
            <tr>
                <td>{{item.subject_name}}</td>
                <td>{{item.score}}</td>
                <form method="DELETE" action="{%url 'gradebook:delete_marks' item.id%}">
                    <td><input type="submit" value="delete"></td>
                </form>
                
            </tr>
            {% endfor %}
            <form method="POST" action="{%url 'gradebook:add_marks' student.id%}">
                {% csrf_token %}
                <tr>
                    <td><input type="text" name="sub_name" placeholder="subject_name" /></td>
                    <td><input type="text" name="score" placeholder="score"/></td>
                    <td><input type="submit" name="add" value="add" /></td>

                </tr>            
            </form>
            
            <form method="POST" action="{%url 'gradebook:update_marks' student.id%}">
                {% csrf_token %}

                <td><input type="text" name="name" placeholder="name" /></td>
                <td><input type="text" name="update_name" placeholder="update name" /></td>
                <td><input type="text" name="update_score" placeholder="update score" /></td>
                <td><input type="submit" value="update"></td>
            </form>
        </table>
    </body>
</html>