shipping/handcrik/urls.py
from django.urls import path
from . import views
urlpatterns =[
    path('', views.home , name='home'),
    path('playgame',views.play_game ,name='play_game'),
]

shipping/package/urls.py
from django.urls import path
from . import views
app_name = 'package'
urlpatterns = [
    # path('', views.index, name='index'),
    path('register', views.register_package, name='register_package'),
    path('login',views.login_view,name='login_view'),
    path('postman',views.postman,name='postman'),
    path('modifypackage/<int:id>', views.modify_package, name='modify'),
    path('package/<int:id>', views.package_detail, name='package_detail'),
    path('logout', views.logout_view, name='logout'),

]

shipping/shipping/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shipping_app/',include('shipping_app.urls')),
    path('package/',include('package.urls')),
]

shipping/shipping_app/urls.py
from django.urls import path
from . import views

app_name = 'shipping_app'

urlpatterns =[
    path('home',views.register,name='register'),
    path('login',views.login_view,name='login_view')
]

shipping/handcrik/models.py
from django.db import models

# Create your models here.

  

shipping/package/models.py
from django.db import models
from datetime import date, timedelta

# Create your models here.
def five_days_from_now():
    return date.today() + timedelta(days=5)

class Package(models.Model):
    phone = models.IntegerField(max_length=50)
    address = models.CharField(max_length=250)
    status = models.CharField(max_length = 50, default='Received')
    eta = models.DateField(default=five_days_from_now)
#su=owner,sai@1234
# user=postmaster
# password=sri@1234

shipping/shipping_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Customer(models.Model):
    phone_number = models.IntegerField()
    delivery_address = models.CharField(max_length=250)
    package_id = models.CharField(max_length=20 ,unique=True)
    status = models.CharField(max_length=40)

class Postman(models.Model):
    user_name = models.CharField(max_length=50 ,unique=True)
    password = models.CharField(max_length=20)
    

shipping/handcrik/views.py
from django.shortcuts import render,redirect
import random

def home(request):
    return render(request, 'handcrik/game.html')

def play_game(request):
    win_messege = ''
    if request.method == 'POST':
        player_choice = int(request.POST.get('player_choice'))
        # print(player_choice)
        computer_choice = random.randint(1, 6)
        score = int(request.session.get('score', 0))
        if player_choice == computer_choice:
            score = 0
            win_messege = 'player_out'
            
          
        else:
            runs = player_choice
            score += runs

        request.session['score'] = score
      
        scorecard = { 'score': score,'win_messege':win_messege,'computer_choice':computer_choice,'player_choice':player_choice,}
        return render(request, 'handcrik/game.html', {'scorecard': scorecard})
    else:
        return redirect('home')

shipping/package/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from . models import Package
# Create your views here.
def register_package(request):
    if request.method == 'GET':
        access = False
        return render(request, 'package/register_package.html')
    if request.method =='POST':
        access = True
        address_ = request.POST.get('address','')
        phone_ = request.POST.get('phone','')
        package = Package(address=address_,phone=phone_)
        package.save()
        package_id = package.id
        return render(request, 'package/register_package.html',{'package_id':package_id,'access':access})
        # return render(request, 'package/register_package.html')
def login_view(request):
    error_message = ''
    if request.method == 'GET':
        return render(request, 'package/login.html')
    if request.method == 'POST':
        username_ = request.POST.get('username','')
        password_ = request.POST.get('password','')
        user = authenticate(request, username=username_, password=password_)
        if user is not None:
            # if user.is_active:
                login(request, user)
                print(username_,password_)
                return redirect( 'package:postman')
        else:
            error_message = ' invalid user'
    return render(request, 'package/login.html',{'error_message':error_message})

@login_required(login_url='package:login_view')
def postman(request):
    package_details = Package.objects.all()
    
    return render(request, 'package/postman.html',{'package_details':package_details})
def logout_view(request):
    logout(request)
    return redirect( 'package:login_view')

@login_required(login_url='package:login_view')
def modify_package(request, id):
    package = Package.objects.get(id=id)
    newstatus = request.POST.get('status',package.status)
    neweta = request.POST.get('eta', package.eta)
    package.status = newstatus
    package.eta = neweta
    package.save()
    return redirect('package:postman')
def package_detail(request,id):
    package = Package.objects.get(id=id)
    return render(request, 'package/package_detail.html',{'package':package})

        
        

shipping/shipping_app/views.py
from django.shortcuts import render,redirect
from . models import  Customer,Postman
from django.contrib.auth import authenticate,login,logout


# Create your views here.
def register(request):
    details=''
    if request.method == 'POST':
        address_ = request.POST.get('address')
        phone_number_ =request.POST.get('phone_number')
        register_ = Customer(address=address_,phone_number=phone_number_)
        register_.save()
        details = {item.package_id : item for item in Customer.objects.filter(customer =register_)}
    return render(request,'shipping_app/home.html')


def login_view(request):
    error_message = ''
    if request.method == 'POST':
        username_ = request.POST.get('username')
        password_ = request.POST.get('password')
        user = authenticate(username=username_,password=password_)
        if user is not None:
            if user.is_active:
                login(request,user)
                return redirect('shipping_app/modifypage.html')
        else:
            error_message = 'Invalid username or password'
            return render('shopping_app/login.html',{'error_message':error_message})
    return redirect('shipping_app:login')

shipping/handcrik/templates/handcrik/game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hand cricket game</title>
    <style>
      
    </style>
</head>
<body>
    <div class="container"> 
        <h3>Hand cricket game</h3>
        {%if scorecard%}
        <p>score:{{scorecard.score}}</p>
        {%endif%}
        {% if not scorecard %}
        <p>No score yet.</p>
        {% endif %} 
        <h2> {{scorecard.win_messege}}</h2>
        <form action="{%url 'play_game'%}" method="post">
            {% csrf_token %}
            player_choice(1-6):<input type="text" name="player_choice" value="{{scorecard.player_choice}}"><br>
            <br>
            <input type="submit" value="rolldice"><br>
            <br>
            computer_choice:<input type="text" value="{{scorecard.computer_choice}}"><br>
        </form><br>
        <br>
    </div>
   

    
    <!-- <input type="submit"  name='continue' value="continue"> -->

   
</body>
</html>

shipping/package/templates/package/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>login</title>
  </head>
  <body>
    <h1>login </h1>
    {{error_message}}
    <form action="{%url 'package:login_view'%}" method="POST">
      {% csrf_token %}
        <div class="form-group">
          <label for="username">user name</label>
          <input name="username" type="text" class="form-control"  >
          
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input name= "password"type="password" class="form-control">
        </div>
       
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <p>Customer? Register a package <a href="{% url 'package:register_package' %}">here.</a></p>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

shipping/package/templates/package/package_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Package {{package.id}}</h3>
    <h5>Phone: {{package.phone}}</h5>
    <h5>Address: {{package.address}}</h5>
    <h6>Status: {{package.status}}</h6>
    <h6>ETA: {{package.eta}}</h6>

    
</body>
</html>

shipping/package/templates/package/postman.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>pacakage_details</title>
    
    <link rel="stylesheet" href="{% static 'package/css/postman.css'%}">
</head>

<body>
    <h1>packages</h1>
    <table>
      <thead>
        <tr>
          <th>id</th>
          <th>adress</th>
          <th>phone</th>
          <th>status</th>
          <th>ETA</th>
          <th>New ETA</th>
        </tr>
      </thead>
      <tbody>
        {% for items in package_details %}
        <tr>
          <td>
            {{ items.id }}
          </td>
          <td>{{ items.address }}</td>
          <td>{{ items.phone }}</td>
          <form method="POST" action="{% url 'package:modify' items.id %}">
            {% csrf_token %}
            <td><input type="text" name="status" value="{{items.status}}"></td>
            <td>{{items.eta}}</td>
            <td><input type="date" name="eta" ></td>
            <td><input type="submit" value="Change status and ETA"></td>
        </form>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  <a href="{%url 'package:logout' %}">logout</a>
</body>
</html>

shipping/package/templates/package/register_package.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }
        h3{
            text-align: center;
            font-weight: 300;
            font-size: 40px;
        }
        .container{
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            width: 100%;
            margin-top: 100px;
            text-align: center;
            border: 1px solid black;
            
            

        }
        .container.tr.td.input{
            margin: 30px;

        }
        
  
    </style>
</head>
<body>
    <h3>register a package</h3>
    <div class="container">
        <form method="POST" action="">
            {% csrf_token %}
            <tr>
                <td>Enter your phone number:<input type="text" name="phone" placeholder="phone"/></td><br>
                <br>
                <br>
                <td>please enter address:<input type="textarea" name="address" placeholder="address" /></td><br>
                <br>
                <br>
                <td><input type="submit" name="submit" value="submit" /></td>
    
            </tr>            
        </form> 
    
    </div>
    {% if access %}
    <p>successfully your package was register! your package id is :{{package_id}}.Track it<a href="{% url 'package:package_detail' package_id%}"> here</a></p>
    {% endif %}
    <p>Already got a tracking id? Check status here:
        <form method="GET" onsubmit="return setAction(this)">
            <input type="text" id="packageid">
            <input type="submit" value="Track">
        </form>
    </p>
    <p>Postmaster? <a href="{% url 'package:login_view' %}">Login here.</a></p>
    <script>
        function setAction(form) {
            var id = document.getElementById("packageid").value
            var url = "{% url 'package:package_detail' id=1 %}".replace(/1/, id)
            form.action = url
        }    
    </script>

  

    
</body>
</html>

shipping/shipping_app/templates/shipping_app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        h3{
            text-align: center;

        }
        .container{
          
            margin: auto;
            width: 50%;
            border: 3px solid green;
            padding: 10px;
        }
    </style>
</head>
<body>
    <h3>register a package</h3>
    <div class="container">
        <form method="POST" action="{%url 'shipping_app:register' %}">
            {% csrf_token %}
            <tr>
                <td><input type="text" name="phone_number" placeholder="phone_number"/></td><br>
                <td><input type="textarea" name="address" placeholder="address" /></td><br>
                <td><input type="submit" name="submit" value="submit" /></td>
    
            </tr>            
        </form>
    
    </div>
    
</body>
</html>

shipping/shipping_app/templates/shipping_app/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>login to ecommerce</title>
        <title>Login Page</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'shopping/login.css' %}">
        <!-- <style>
            body {
                background-color: #f1f1f1;
                font-family: Arial, sans-serif;
                font-size: 16px;
                margin: 0;
                padding: 0;
            }
            .container {
                background-color: #fff;
                border-radius: 10px;
                box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
                margin: 50px auto;
                max-width: 500px;
                padding: 50px;
                text-align: center;
            }
            h1 {
                color: #333;
                font-size: 24px;
                margin-bottom: 30px;
            }
            input[type="text"],
            input[type="password"] {
                background-color: #f1f1f1;
                border: none;
                border-radius: 5px;
                box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
                margin-bottom: 20px;
                padding: 10px;
                width: 100%;
            }
            input[type="submit"] {
                background-color: #4CAF50;
                border: none;
                border-radius: 5px;
                box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
                color: #fff;
                cursor: pointer;
                margin-top: 20px;
                padding: 10px;
                width: 100%;
            }
            input[type="submit"]:hover {
                background-color: #3e8e41;
            }
        </style> -->
    </head>
    <body>
        <div class="container">
            <h1>Login</h1>
            
            <form method="POST" action="{% url 'shopping:login' %}">
                <h3>{{error_message}}</h3>
                {% csrf_token %}
                <input type="text" name = "username" placeholder="Username">
                <input type="password" name = "password" placeholder="Password">
                <input type="submit" value="Login">
            </form>
        </div>
    </body>
</html>